SHELL := /bin/bash
PREFIX ?= $(HOME)/.local
BINDIR ?= $(PREFIX)/bin
LIBEXEC ?= $(PREFIX)/libexec/git-account
DIST ?= dist

LIBS := lib/common.sh lib/profiles.sh lib/detect.sh lib/auth.sh lib/sign.sh lib/apply.sh

.PHONY: help test lint install uninstall bundle clean

help:
	@echo "Targets:"
	@echo "  test      Run the bats test suite"
	@echo "  lint      Run shellcheck (if installed)"
	@echo "  install   Copy tree to LIBEXEC and symlink git-account into BINDIR"
	@echo "  uninstall Remove installed files"
	@echo "  bundle    Build a single self-contained script at $(DIST)/git-account"
	@echo "  clean     Remove build artifacts"

test:
	bats tests

lint:
	@command -v shellcheck >/dev/null 2>&1 && shellcheck -x git-account hooks/pre-commit install.sh $(LIBS) || echo "shellcheck not installed; skipping"

install:
	@mkdir -p "$(LIBEXEC)/lib" "$(LIBEXEC)/hooks" "$(BINDIR)"
	@cp git-account "$(LIBEXEC)/git-account"
	@cp $(LIBS) "$(LIBEXEC)/lib/"
	@cp hooks/pre-commit "$(LIBEXEC)/hooks/pre-commit"
	@chmod +x "$(LIBEXEC)/git-account" "$(LIBEXEC)/hooks/pre-commit"
	@ln -sf "$(LIBEXEC)/git-account" "$(BINDIR)/git-account"
	@echo "Installed to $(LIBEXEC), linked $(BINDIR)/git-account"

uninstall:
	@rm -f "$(BINDIR)/git-account"
	@rm -rf "$(LIBEXEC)"
	@echo "Uninstalled."

# Concatenate lib/*.sh into the entrypoint so it runs as a single file with no
# external lib dependency. The generated script keeps a self-relative hooks dir.
bundle:
	@mkdir -p "$(DIST)"
	@{ \
	  echo '#!/usr/bin/env bash'; \
	  echo '# git-account (bundled single-file build) - generated by make bundle'; \
	  echo 'set -euo pipefail'; \
	  echo 'VERSION="0.1.0"'; \
	  echo 'GA_ROOT="$$(cd "$$(dirname "$${BASH_SOURCE[0]:-$$0}")" >/dev/null 2>&1 && pwd)"'; \
	  echo 'GA_HOOKS_DIR="$$GA_ROOT/hooks"'; \
	  for f in $(LIBS); do echo "# --- inlined $$f ---"; sed -e '/^# shellcheck/d' "$$f"; done; \
	  sed -n '/^# ---------------------------------------------------------------------------/,$$p' git-account; \
	} > "$(DIST)/git-account"
	@chmod +x "$(DIST)/git-account"
	@echo "Wrote $(DIST)/git-account (single-file). Copy it anywhere on PATH."

clean:
	@rm -rf "$(DIST)"
